# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.cache/wt} [current_project]
set_property parent.project_path {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {d:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/Lab9/Basaadhi_Adheesha/Adder_bit_3/Adder_bit_3.srcs/sources_1/new/BIT_3_ADDER.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/Lab9/Sandaru_200729V/DigiLab09-20220710T072741Z-001/DigiLab09/8-way 4-bit multiplexer with 3-to-8 decoder/Decoders/Decoder_2_to_4.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/new/Decoder_3_to_8.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/Lab9/Basaadhi_Adheesha/Adder_bit_3/Adder_bit_3.srcs/sources_1/new/FA.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/Lab9/Upeksha_200672M/Adder_subtractor_Lab9-20220710T144112Z-001/Adder_subtractor_Lab9/Full_Adder.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/Lab9/Basaadhi_Adheesha/Adder_bit_3/Adder_bit_3.srcs/sources_1/new/HA.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/new/Instruction_Decoder.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/new/LUT_16_7.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/8-WAY4~2/MUX_8_~1.VHD}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/Lab9/Sandaru_200729V/DigiLab09-20220710T072741Z-001/DigiLab09/2-way 3-bit multiplexer/Mux_2_way_3_bit.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/Lab9/Sandaru_200729V/DigiLab09-20220710T072741Z-001/DigiLab09/2-way 4-bit multiplexer/Mux_2_way_4_bit.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/new/ProgramCounter.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/Lab9/Anoshan_200040B/ProgramROM.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/new/Reg.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/new/RegisterBank.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/Lab9/Basaadhi_Adheesha/Program_counter/Program_counter.srcs/sources_1/new/Slow_Clk.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/imports/Lab9/Upeksha_200672M/Adder_subtractor_Lab9-20220710T144112Z-001/Adder_subtractor_Lab9/addsub.vhd}
  {D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/sources_1/new/NanoProcessor.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/constrs_1/imports/Computer organizaton and data structure/Basys3Labs.xdc}}
set_property used_in_implementation false [get_files {{D:/1. CSE/Xilinx_Vivado/Lab_9/Lab_9_v12/Lab_9_v11.srcs/constrs_1/imports/Computer organizaton and data structure/Basys3Labs.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top NanoProcessor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NanoProcessor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file NanoProcessor_utilization_synth.rpt -pb NanoProcessor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
